name: Deploy to Staging

on:
  workflow_dispatch:

concurrency:
  group: staging_environment
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Pull YAML data
        run: ./tools/sync_data.sh
      - name: Build the project
        run: yarn build
      - name: Deploy to Github page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: staging.theyworkforus.wevis.info
